Unit Stale;

interface

const
  { ilo˜† dni w tygodniu }
  IloscDni = 5;

  { komendy programu }
  cmNauczycielAdd   = 100;
  cmNauczycielDel   = 101;
  cmNauczycielEdit  = 102;
  cmPrzedmiotAdd    = 110;
  cmPrzedmiotDel    = 111;
  cmPrzedmiotEdit   = 112;
  cmKlasaAdd        = 120;
  cmKlasaDel        = 121;
  cmKlasaEdit       = 122;
  cmSalaAdd         = 130;
  cmSalaDel         = 131;
  cmSalaEdit        = 132;
  cmDzwonekAdd      = 140;
  cmDzwonekDel      = 141;
  cmDzwonekEdit     = 142;
  cmLekcjaAdd       = 150;
  cmLekcjaDel       = 151;
  cmLekcjaEdit      = 152;
  cmArchiwizacja    = 160;
  cmOdzysk          = 161;
  cmAboutBox        = 170;
  cmPlanNauczyciela = 180;
  cmPlanKlasy       = 181;
  cmClickActiveText = 250;
  cmChooseFromList  = 251;
  cmUpdateLists     = 1000;
  cmDataBaseChanged = 1001;

  { konteksty pomocy }
  hcNauczycielAdd   = $1100;
  hcNauczycielDel   = $1101;
  hcNauczycielEdit  = $1102;
  hcPrzedmiotAdd    = $1110;
  hcPrzedmiotDel    = $1111;
  hcPrzedmiotEdit   = $1112;
  hcKlasaAdd        = $1120;
  hcKlasaDel        = $1121;
  hcKlasaEdit       = $1122;
  hcSalaAdd         = $1130;
  hcSalaDel         = $1131;
  hcSalaEdit        = $1132;
  hcDzwonekAdd      = $1140;
  hcDzwonekDel      = $1141;
  hcDzwonekEdit     = $1142;
  hcLekcjaAdd       = $1150;
  hcLekcjaDel       = $1151;
  hcLekcjaEdit      = $1152;

  hcSlownikiMenu    = $2000;
  hcNauczycieleMenu = $2001;
  hcPrzedmiotyMenu  = $2002;
  hcKlasyMenu       = $2003;
  hcSaleMenu        = $2004;
  hcDzwonkiMenu     = $2005;

  hcPlanLekcjiMenu  = $2006;
  hcSystemMenu      = $2007;
  hcPomocMenu       = $2008;
  hcAboutBox        = $2009;
  hcPlanKlasy       = $2010;
  hcClickActiveText = $2011;
  hcPlanNauczyciela = $2012;
  hcArchiwizacja    = $2013;
  hcOdzysk          = $2014;
  hcQuit            = $2015;
  hcHelp            = $2016;

implementation

begin
end.
