Unit Stale;

interface

const { Staˆe determinuj¥ce dˆugo˜ci ˆaäcuch¢w w typach danych }
  slSkrot           =  5;
  slImieNazwisko    = 40;
  slNazwaPrzedmiotu = 40;
  slNumerKlasy      =  5;
  slNazwaSali       = 30;
  slNumerSali       =  5;

const { Staˆe definiuj¥ce komendy programu }
  cmDodajNauczyciela    = $1200;
  cmPoprawNauczyciela   = $1201;
  cmUsunNauczyciela     = $1202;
  cmDodajPrzedmiot      = $1203;
  cmPoprawPrzedmiot     = $1204;
  cmUsunPrzedmiot       = $1205;
  cmDodajKlase          = $1206;
  cmPoprawKlase         = $1207;
  cmUsunKlase           = $1208;
  cmDodajSale           = $1209;
  cmPoprawSale          = $120A;
  cmUsunSale            = $120B;
  cmDodajDzwonek        = $120C;
  cmPoprawDzwonek       = $120D;
  cmUsunDzwonek         = $120E;

  cmDodajLekcje         = $2000;
  cmPoprawLekcje        = $2001;
  cmUsunLekcje          = $2002;

  cmDataChanged         = $9FFF;
  cmShowPlanNauczyciela = $4000;
  cmShowPlanKlasy       = $4001;
  cmArchiwizacja        = $4002;
  cmOdzysk              = $4003;
  cmOProgramie          = $5000;
  cmPrint               = $5001;

implementation

begin

end.
